version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    tty: true
    container_name: customerservice
    volumes:
      - $PWD:/go/src/customerservice
    depends_on:
      - etcd1
      - etcd2
      - etcd3
#    command: /bin/bash -c "cd src/customerservice/cmd/ && go run main.go"

    ports:
    - "8088:8088"
    - "7000:7000"
    - "2345:2345"

  app2:
    build:
      context: .
      dockerfile: app.dockerfile
    tty: true
    container_name: customerservice2
    volumes:
      - $PWD:/go/src/customerservice
    depends_on:
      - etcd1
      - etcd2
      - etcd3
#    command: /bin/bash -c "cd src/customerservice/cmd/ && go run main.go"
    ports:
      - "8089:8088"
      - "7001:7000"
      - "2346:2345"

  app3:
    build:
      context: .
      dockerfile: app.dockerfile
    tty: true
    container_name: customerservice3
    volumes:
      - $PWD:/go/src/customerservice
    depends_on:
      - etcd1
      - etcd2
      - etcd3
#    command: /bin/bash -c "cd src/customerservice/cmd/ && go run main.go"
    ports:
      - "8090:8088"
      - "7002:7000"
      - "2347:2345"

  etcd1:
    image: bitnami/etcd
    tty: true
    container_name: etcd1
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_NAME: "etcd1"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
    ports:
      - "23791:2379"
      - "23801:2380"


  etcd2:
    image: bitnami/etcd
    tty: true
    container_name: etcd2
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_NAME: "etcd2"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
    ports:
      - "23792:2379"
      - "23802:2380"


  etcd3:
    image: bitnami/etcd
    tty: true
    container_name: etcd3
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_NAME: "etcd3"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
    ports:
      - "23793:2379"
      - "23803:2380"


