appmode = "development"

[etcd]
addr = ["etcd1:2379"]
#addr = ["127.0.0.1:2379"]

[mysql]
ip = "localhost"
port = 3306
root = "root"
password = "mysql"

[common]
HttpPort = 8088
RPCPort =7000
# 对称加密key
CryptoKey = "Adba723b7fe06819"
ServerPrefix = "ws/server/"

[logConf]
LogPath = "./Log/"
LogSave = 3
HideKeys = false
Level = "debug"
