// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	AppId                string   `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Message) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Message) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type BroadcastData struct {
	AppId                string   `protobuf:"bytes,1,opt,name=AppId,proto3" json:"AppId,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	FromClientId         string   `protobuf:"bytes,4,opt,name=FromClientId,proto3" json:"FromClientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastData) Reset()         { *m = BroadcastData{} }
func (m *BroadcastData) String() string { return proto.CompactTextString(m) }
func (*BroadcastData) ProtoMessage()    {}
func (*BroadcastData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{1}
}

func (m *BroadcastData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastData.Unmarshal(m, b)
}
func (m *BroadcastData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastData.Marshal(b, m, deterministic)
}
func (m *BroadcastData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastData.Merge(m, src)
}
func (m *BroadcastData) XXX_Size() int {
	return xxx_messageInfo_BroadcastData.Size(m)
}
func (m *BroadcastData) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastData.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastData proto.InternalMessageInfo

func (m *BroadcastData) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BroadcastData) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BroadcastData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *BroadcastData) GetFromClientId() string {
	if m != nil {
		return m.FromClientId
	}
	return ""
}

type Reply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9efa92dae3d6ec46, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Reply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*BroadcastData)(nil), "pb.BroadcastData")
	proto.RegisterType((*Reply)(nil), "pb.Reply")
}

func init() { proto.RegisterFile("customer.proto", fileDescriptor_9efa92dae3d6ec46) }

var fileDescriptor_9efa92dae3d6ec46 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x24, 0x49, 0x03, 0xc9, 0x2b, 0x20, 0x78, 0x62, 0x88, 0x3a, 0x55, 0x5e, 0xa8, 0x84, 0x48,
	0x25, 0x18, 0x99, 0x68, 0x10, 0x52, 0x87, 0x2e, 0x81, 0x89, 0x09, 0x3b, 0xb6, 0x2a, 0xa4, 0xb6,
	0x7e, 0xc4, 0x66, 0xe8, 0xdf, 0x23, 0xbf, 0xa6, 0x45, 0x91, 0xe8, 0x76, 0x77, 0x7e, 0xba, 0xf3,
	0x1d, 0x5c, 0x36, 0x3f, 0xce, 0xdb, 0xb5, 0x69, 0x4b, 0x6a, 0xad, 0xb7, 0x18, 0x93, 0x12, 0x0d,
	0x9c, 0x2d, 0x8c, 0x73, 0x72, 0x69, 0xf0, 0x06, 0xd2, 0x67, 0xa2, 0xb9, 0x2e, 0xa2, 0x71, 0x34,
	0xc9, 0xeb, 0x1d, 0xc1, 0x11, 0x64, 0xd5, 0xea, 0xcb, 0x6c, 0xfc, 0x5c, 0x17, 0x31, 0x3f, 0x1c,
	0x38, 0x22, 0x0c, 0xde, 0xb7, 0x64, 0x8a, 0x64, 0x1c, 0x4d, 0xd2, 0x9a, 0x71, 0xd0, 0x5e, 0xa4,
	0x97, 0xc5, 0x80, 0x6f, 0x19, 0x8b, 0x6f, 0xb8, 0x98, 0xb5, 0x56, 0xea, 0x46, 0x3a, 0x1f, 0x84,
	0x23, 0x51, 0x7b, 0xbb, 0xf8, 0x1f, 0xbb, 0xe4, 0xcf, 0x0e, 0x05, 0x9c, 0xbf, 0xb6, 0x76, 0x7d,
	0xf8, 0xd6, 0x2e, 0xaa, 0xa7, 0x89, 0x7b, 0x48, 0x6b, 0x43, 0xab, 0x6d, 0x30, 0xa8, 0xac, 0x36,
	0x9c, 0x94, 0xd6, 0x8c, 0xf1, 0x0a, 0x92, 0x85, 0x5b, 0x76, 0x75, 0x02, 0x7c, 0xf8, 0x84, 0xac,
	0xea, 0xc6, 0xc1, 0x5b, 0x18, 0xbe, 0x99, 0x8d, 0xde, 0xcf, 0x32, 0x2c, 0x49, 0x95, 0x1d, 0x19,
	0xe5, 0x81, 0xb0, 0xb1, 0x38, 0xc1, 0x3b, 0xc8, 0xb9, 0x56, 0x25, 0x9d, 0xc7, 0xeb, 0xf0, 0xd2,
	0x6b, 0xd9, 0x3b, 0x9e, 0xc1, 0x47, 0x56, 0x4e, 0x49, 0x4d, 0x9f, 0x48, 0xa9, 0x53, 0xde, 0xff,
	0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x23, 0x7a, 0xb5, 0x5a, 0x91, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Reply, error)
	BroadCast(ctx context.Context, in *BroadcastData, opts ...grpc.CallOption) (*Reply, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/pb.Customer/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) BroadCast(ctx context.Context, in *BroadcastData, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/pb.Customer/BroadCast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	SendMessage(context.Context, *Message) (*Reply, error)
	BroadCast(context.Context, *BroadcastData) (*Reply, error)
}

// UnimplementedCustomerServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func (*UnimplementedCustomerServer) SendMessage(ctx context.Context, req *Message) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedCustomerServer) BroadCast(ctx context.Context, req *BroadcastData) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadCast not implemented")
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Customer/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_BroadCast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).BroadCast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Customer/BroadCast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).BroadCast(ctx, req.(*BroadcastData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Customer_SendMessage_Handler,
		},
		{
			MethodName: "BroadCast",
			Handler:    _Customer_BroadCast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer.proto",
}
